server {
    listen 80;
    client_max_body_size 250m;

    location /static/ {
        alias /app/static/;
        try_files $uri =404;
        expires 7d;
    }

    location /storage/ {
        alias /app/storage/public/;
        try_files $uri =404;
        expires 7d;
    }

    location / {
        proxy_pass http://geode-index:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
